apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-scale-test
  labels:
    app: nginx-scale-test
spec:
  replicas: 1 # Start with a single replica to test the deployment
  selector:
    matchLabels:
      app: nginx-scale-test
  template:
    metadata:
      labels:
        app: nginx-scale-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6 # Use a specific, well-known tag to avoid "latest" image issues
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "64Mi"
