apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-scale-test
  labels:
    app: nginx-scale-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-scale-test
  template:
    metadata:
      labels:
        app: nginx-scale-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest    # official nginx image from Docker Hub
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-scale-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
